config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'registration' }
  root to: "home#index"
  namespace :admin do
    resources :barber
    resources :schedule, only: [:index, :new, :create]
      get 'schedule/gcal_redirect'
      get 'schedule/cutz_callback'
      get 'schedule/new_calendar'
      get 'schedule/add_appointment'
      get 'schedule/cancel_appointment'
      get 'schedule/get_calendar_id'
      get 'schedule/get_list'
  end

  resources :barber do
      resources :galleries, except: [:new, :create]
      resources :appointments, only: [:index ,:new, :create] do
        get 'appointments/welcome'
      end
      post 'referrals/question'
  end

  get "/auth/:provider/callback", to: "auth#callback"
  resources :calendar

  get 'galleries/new'
  post 'galleries/create'

  post 'barber/find'

end

app/controllers/admin/barber_controller.rb
class Admin::BarberController < ApplicationController

  def show
      @barber = User.where(id: params[:id]).take
      @clients = @barber.appointments.all
      if params[:appointment_type] == 'request_all'
        @clients = @barber.appointments.all
       elsif params[:appointment_type] == 'booked_appointments'
        @clients = @barber.appointments.all
      end
      @referrals = @barber.referrals
  # to retrieve a calendar event GET https://www.googleapis.com/calendar/v3/calendars/calendarId/events/eventId
  # to post a new event POST https://www.googleapis.com/calendar/v3/calendars/calendarId/events
  end

end

app/controllers/barber_controller.rb
class BarberController < ApplicationController

  def find
    @barber = User.where(unique_code: params[:barber_code]).take
    if @barber
       redirect_to barber_galleries_path(@barber.id)
    elsif @barber == nil
       redirect_to root_path
    end
  end


#TODO: INSERT STRONG PARAMS HERE FOR UNIQUE_CODE


end

app/helpers/barber_helper.rb
module BarberHelper
end

app/views/barber/show.html.erb
<style>

</style>
  <center>
    <div class="picture-frame">
      <%= image_tag('scissors.png', size: "150x100")%>
    </div>
  
  <div class="toobar">
    <!-- <link_to 'Authorize Google Calendar', schedule_gcal_redirect_path ><br> -->
    <%=link_to 'Appointment', admin_barber_path(current_user.id, appointment_type: 'request_all'), class:'showbutton' %></br>
    <%=link_to 'Guestbook', '#', class:'showbutton' %></br>
    <%=link_to 'New Customers' , '#', class:'showbutton'%></br> <!-- Customers as a result of a discount url -->
    <%=link_to 'Stats', '#', class:'showbutton'%></br> <!-- Tracking new customers , old customers, appointments this week over last week -->
    <%=link_to 'Settings', '#', class: 'showbutton' %>
    <%=link_to 'Authorize Free Busy', '/auth/cronofy', class:'showbutton' %></br>
  </div>
   </center>

  
    <div class='col-md-8'>
      <%if @clients == nil%>
         <p>There are no appointments yet</p>
      <%else%>
      <% @clients.each do |appt|%>
        <div class="card">
        <p><%=appt.schedule_day.strftime('%m-%A-%Y')%> @ <%= appt.start_time.strftime("%I:%M %P")%></p>
          <%= link_to 'Approve',  schedule_add_appointment_path(appt_id: appt.id) %> |
          <%= link_to 'Cancel',  schedule_cancel_appointment_path(appt_id: appt.id) %>
        </div>
        <%end%>
      <%end%>

    <div>



<!-- </div> -->

<!-- TODO: fix the barber sign up flow and adding appointment process as to not need links-->
<br><br>
<!--link_to 'Create New Barber Calendar', schedule_new_calendar_path, class: 'btn btn-primary' %><br><br>
# <link_to 'Get Calendar Id', schedule_get_calendar_id_path, class: 'btn btn-primary'%><br><br>--> 