config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'registration' }
  root to: "home#index"
  namespace :admin do
    resources :barber
    resources :schedule, only: [:index, :new, :create]
      get 'schedule/gcal_redirect'
      get 'schedule/cutz_callback'
      get 'schedule/new_calendar'
      get 'schedule/add_appointment'
      get 'schedule/cancel_appointment'
      get 'schedule/get_calendar_id'
      get 'schedule/get_list'
  end

  resources :barber do
      resources :galleries, except: [:new, :create]
      resources :appointments, only: [:index ,:new, :create] do
        get 'appointments/welcome'
      end
      post 'referrals/question'
  end

  get "/auth/:provider/callback", to: "auth#callback"
  resources :calendar

  get 'galleries/new'
  post 'galleries/create'

  post 'barber/find'

end

app/models/gallery.rb
# == Schema Information
#
# Table name: galleries
#
#  id                 :integer          not null, primary key
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  hairstyle_image_id :string
#

class Gallery < ActiveRecord::Base
  attachment :hairstyle_image


  


end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  def index
    @referral = Referral.new
      if params[:items] == 'grid-view'
         @photo = Gallery.all 
        elsif 
           @photos = ['Haircut', 'Shapeup', 'Hot Towel Shave', 'Fade' , 'Beard Trim'] 
      end
  end

  def new 
    @photo = Gallery.new

  end 

  def create 
    @photo = Gallery.new(photo_params)
    if @photo.save 
    flash[:notice] = "Image Added"
    redirect_to root_path
    else 
    render :new
    end
  end

  def destroy 
    @photo = Gallery.find(id: params[:id])
    if @photo.destroy
    flash[:notice] = "Photo was successfully deleted"
    render :new
    end
  end

  private 
  def photo_params
    params.require(:gallery).permit(:hairstyle_image)
  end

end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  def index
  end
end

app/helpers/gallery_helper.rb
module GalleryHelper
  
end

app/views/galleries/index.html.erb
<div class="container col-xs-6 col-md-12">

  <h1 class="user-action">Hairstyle</h1><hr>
<!--   <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal">
    Referral Question 
  </button></br> -->
<!--   <link_to 'Fade', '#', class: 'showbutton' %> | < link_to 'Caeser', '#', class: 'showbutton' %> | <link_to 'MoHawk', '#', class: 'showbutton' >  -->
 <%=link_to 'item-view', barber_galleries_path(params[:barber_id])%> |
 <strike><a href='#' id="mytooltip" data-toggle='tooltip' data-placement="top" title="Coming Soon">grid view</a></strike>
 <!-- barber_galleries_path(params[:barber_id], items: 'grid-view' -->

<% if @photo %>
<div class="grid photo-wall">
  <% @photo.each do |photo|%>
  <div class="grid-item">
    <%= link_to new_barber_appointment_path(:style_id => photo.id, :q => 'today' ) do %>
    <%= image_tag attachment_url(photo, :hairstyle_image, :fill, 300, 300, format: "jpg")%>
    <%end%>
  </div>
  <%end%>
</div>
</div>
  <%else%>
      </br></br>
      <center>
     <% @photos.each do |item| %>
      <div class='box'>
      <span class='anchor'><%=link_to new_barber_appointment_path(style: item, q: 'today') do %>
      <center><p><%= item %></p></center>
      <%end%><span>
      </div>
      </br>

      <%end%>
      </center>

<%end%>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="myModalLabel"> Were you Referred?</h4>
      </div>
      <div class="modal-body">
          <div class="input-group">
          <%= form_for @referral , url: barber_referrals_question_path do |f|%>
          <%= f.radio_button :state, 'true' %>
          <%= label :state, 'yes' %>
          <%= f.radio_button :state, 'false' %>
          <%= label :state, 'no' %>
          <%=submit_tag 'submit', class: 'btn btn-primary'%>
          <%end%>
          </div>
      </div>
    </div>
  </div>
</div>
<script type='text/javascript'> 

$(function () {
  $('#mytooltip').tooltip()
})

$('.box').on('mouseenter', function(){
    $(this).fadeIn('slow', function() {
      $(this).css("background-color", "#bcd8bc");
    });
})
$('.box').on('mouseleave', function(){
    $(this).css("background-color",  " #d3d3d3");
})

</script>

app/views/galleries/new.html.erb
<div class="col-md-12 uploader">
  <%= form_for @photo , url:  galleries_create_path do |form| %>
  <%= form.attachment_field :hairstyle_image %>
  </br>
  <%= form.submit "Upload Styles"%>
  <% end %>
</div>